name: 🐛 Bug Report
description: 버그를 신고합니다.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: 🔍 어떤 문제가 발생했나요?
      placeholder: 예) 버튼을 눌러도 페이지가 이동하지 않음
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 🧪 재현 방법
      placeholder: |
        1. 홈으로 이동
        2. "시작" 버튼 클릭
        3. 오류 발생
  - type: dropdown
    id: device
    attributes:
      label: 🧾 테스트 환경
      options:
        - iOS Simulator
        - iPhone 실제기기
        - 기타
  - type: input
    id: version
    attributes:
      label: 📱 앱 / OS 버전
      placeholder: 예) iOS 17.3, 앱 1.0.2