name: 🚀 Feature Request
description: 새로운 기능을 제안합니다.
title: "[Feat] "
labels: ["feature"]
body:
  - type: textarea
    id: what
    attributes:
      label: 🙋 어떤 기능인가요?
      placeholder: 예) 사용자가 다크모드를 설정할 수 있는 기능
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: 🛠️ Todo !
      placeholder: 예) ViewModel 구현, 스타일 시트 세팅 완료 등
  - type: input
    id: branch
    attributes:
      label: 🌿 작업 브랜치
      placeholder: 예) feat/darkmode-toggle
  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ 스크린샷 (선택)
      placeholder: 여기에 이미지나 화면 캡처를 드래그해서 올려주세요. 설명이 필요한 경우 함께 적어주세요.
  - type: textarea
    id: reference
    attributes:
      label: 🔗 참고 자료
      placeholder: 예) Figma 시안, Notion 문서, 관련 링크 등